apiVersion: v2
name: cinc-console
description: Web console for a Cinc/Chef Infra Server
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/tas50/cinc-console
sources:
  - https://github.com/tas50/cinc-console
keywords:
  - cinc
  - chef
  - infra
  - console
